// src/modules/admin/admin.vue
<script lang="tsx">
import axios from 'axios';
import { Component, Vue } from 'vue-property-decorator';

@Component({})
export default class AdminPage extends Vue {
  private async sendResetToDefaultDataAsync() {
    await axios.post('admin/resetToDefaultData');
  }

  render() {
    return (
      <div class='page'>
        <div class='columns'>
          <div class='column is-12-tablet is-6-desktop is-8-widescreen tree-column'>
            <h1 class='title'>
              Admin
            </h1>

            <button
              class='button is-danger'
              onClick={() => this.sendResetToDefaultDataAsync()}
            >
              <span>Reset to default data</span>
              <span class='icon is-small'>
                <fa-icon icon='exclamation' />
              </span>
            </button>
          </div>
        </div>
      </div>
    );
  }
}
</script>

<style scoped lang="scss">
</style>

// src/ui/modules/admin/admin.tsx
import { resetToDefaultData } from 'src/application/admin/commands/reset-to-default-data';
import { stateful } from 'src/ui/infrastructure/stateful-component';
import { DangerButton } from 'src/ui/shared/common-components/button';
import { Page } from 'src/ui/shared/common-components/layout/page';

export interface AdminPageProps {
}

export interface AdminPageState {
}

const initialState: AdminPageState = {};

export const AdminPage = stateful<AdminPageState, AdminPageProps>(
  initialState,
  {},
  function AdminPage() {
    return (
      <Page title='Admin'>
        <div>
          <DangerButton
            label='Reset to default data'
            icon='exclamation'
            onClick={sendResetToDefaultDataAsync}
          />
        </div>
      </Page>
    );
  },
);

async function sendResetToDefaultDataAsync() {
  await resetToDefaultData();
}

export default AdminPage;
