// src/ui/app/configuration/predicate-templates-page/predicate-template-dialog/predicate-template-dialog.component.ts
import { ChangeDetectionStrategy, Component, Input, OnDestroy } from '@angular/core';
import { ActionsSubject } from '@ngrx/store';
import { Subscription } from 'rxjs';
import { delay, filter, map } from 'rxjs/operators';

import {
  CancelPredicateTemplateDialogAction,
  PredicateTemplateDialogClosedAction,
  PredicateTemplateDialogSubmitSuccessfulAction,
  SubmitPredicateTemplateDialogAction,
} from './predicate-template-dialog.actions';
import { PredicateTemplateDialogState } from './predicate-template-dialog.state';

@Component({
  selector: 'sim-predicate-template-dialog',
  templateUrl: './predicate-template-dialog.component.html',
  styleUrls: ['./predicate-template-dialog.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PredicateTemplateDialogComponent implements OnDestroy {
  @Input() state: PredicateTemplateDialogState;

  private subscriptions: Subscription[] = [];

  constructor(private actionsSubject: ActionsSubject) {
    // this signals the end of the fade out animation of the dialog which
    // allows the state to set the properties required to ensure all
    // animations play properly
    this.subscriptions.push(
      actionsSubject.pipe(
        filter(a => a.type === PredicateTemplateDialogSubmitSuccessfulAction.TYPE || a.type === CancelPredicateTemplateDialogAction.TYPE),
        map(() => new PredicateTemplateDialogClosedAction()),
        delay(200),
      ).subscribe(actionsSubject)
    );
  }

  cancelDialog() {
    this.actionsSubject.next(new CancelPredicateTemplateDialogAction());
  }

  submitDialog() {
    if (this.state.formState.isInvalid) {
      return;
    }

    this.actionsSubject.next(new SubmitPredicateTemplateDialogAction(this.state.formState.value, this.state.templateId));
  }

  ngOnDestroy() {
    this.subscriptions.forEach(s => s.unsubscribe());
  }
}

<form [ngrxFormState]="state.formState">
  <div class="modal"
       [class.is-active]="state.dialogIsOpen && !state.dialogIsClosing">
    <div class="modal-background"></div>
    <div class="modal-card">

      <header class="modal-card-head">
        <p class="modal-card-title"
           *ngIf="state.isNewItem">
          Create new predicate template
        </p>
        <p class="modal-card-title"
           *ngIf="!state.isNewItem">
          Edit predicate template
        </p>
      </header>

      <!--
        We remove the body from the DOM while the dialog is not open to
        prevent any animations from playing when the dialog is opened.
      -->
      <section class="modal-card-body"
               *ngIf="state.dialogIsOpen">
        <sim-predicate-template-form [formState]="state.formState"></sim-predicate-template-form>
      </section>

      <footer class="modal-card-foot justify-content flex-end">
        <button class="button is-danger is-outlined"
                type="button"
                (click)="cancelDialog()"
                [disabled]="state.isSaving">
          Cancel
        </button>
        <button class="button is-success"
                [class.is-loading]="state.isSaving"
                (click)="submitDialog()"
                [disabled]="state.formState.isInvalid && state.formState.isSubmitted">
          Save
        </button>
      </footer>
    </div>
  </div>
</form>

// src/ui-vue/predicate-templates/predicate-template-dialog.vue
<script lang="tsx">
import { Component, Prop } from 'vue-property-decorator';
import TsxComponent from '../tsx-component';

interface PredicateTemplateDialogProps {
  dialogIsOpen: boolean;
}

@Component({
  components: {},
})
export default class PredicateTemplateDialog extends TsxComponent<PredicateTemplateDialogProps> implements PredicateTemplateDialogProps {
  @Prop() dialogIsOpen = false;
  dialogIsClosing = false;
  isNewItem = true;
  isSaving = false;
  formState: any = {};

  submitDialog() {
    // g
  }

  cancelDialog() {
    // g
  }

  render() {
    if (!this.dialogIsOpen) {
      return null;
    }

    return (
      <form ngrxFormState='state.formState'>
        <div class={`modal${this.dialogIsOpen && !this.dialogIsClosing ? ` is-active` : ``}`}>
          <div class='modal-background'></div>
          <div class='modal-card'>

            <header class='modal-card-head'>
              <p class='modal-card-title'>
                { this.isNewItem ? `Create new predicate template` : `Edit predicate template` }
              </p>
            </header>

            {
              /*
                We remove the body from the DOM while the dialog is not open to
                prevent any animations from playing when the dialog is opened.
              */
            }

            { this.dialogIsOpen &&
              <section class='modal-card-body'>
                <sim-predicate-template-form formState='state.formState'></sim-predicate-template-form>
              </section>
            }

            <footer class='modal-card-foot justify-content flex-end'>
              <button class='button is-danger is-outlined'
                      type='button'
                      onClick={() => this.cancelDialog()}
                      disabled={this.isSaving}>
                Cancel
              </button>
              <button class={`button is-success${this.isSaving ? `is-loading` : ``}`}
                      onClick={() => this.submitDialog()}
                      disabled={this.formState.isInvalid && this.formState.isSubmitted}>
                Save
              </button>
            </footer>
          </div>
        </div>
      </form>
    );
  }
}
</script>

<style scoped lang="scss">
</style>
