// src/modules/predicate-template/predicate-template-dialog.vue
<script lang="tsx">
import { Action, createFormGroupState, FormGroupState, formStateReducer } from 'pure-forms';
import { Component } from 'vue-property-decorator';
import { Emit, Form, TsxComponent } from '../../ui-infrastructure';
import PredicateTemplateForm from './predicate-template-form.vue';
import { PredicateTemplateData, PredicateTemplateFormValue, PredicateTemplateState } from './predicate-template.types';
import { validatePredicateTemplateForm } from './predicate-template.validation';

export interface PredicateTemplateDialogProps {
  onSubmit: (data: PredicateTemplateData, id?: string) => any;
}

export const EMPTY_PREDICATE_TEMPLATE_FORM_VALUE: PredicateTemplateFormValue = {
  name: '',
  description: '',
  evalFunctionBody: '',
  parameters: [],
};

const createFormState = (value = EMPTY_PREDICATE_TEMPLATE_FORM_VALUE) =>
  Object.freeze(validatePredicateTemplateForm(createFormGroupState('predicateTemplateDialog', value)));

function formReducer(state: FormGroupState<PredicateTemplateFormValue>, action: Action) {
  return Object.freeze(validatePredicateTemplateForm(formStateReducer(state, action)));
}

@Component({})
export default class PredicateTemplateDialog extends TsxComponent<PredicateTemplateDialogProps> implements PredicateTemplateDialogProps {
  private dialogIsOpen = false;
  private templateId: string | undefined;

  private formState = createFormState();

  openForNewTemplate() {
    this.templateId = undefined;
    this.dialogIsOpen = true;
    this.formState = createFormState();
  }

  openForExistingTemplate(template: PredicateTemplateState) {
    this.templateId = template.id;
    this.dialogIsOpen = true;
    const { id, version, ...rest } = template;
    this.formState = createFormState(rest);
  }

  @Emit()
  onSubmit(_1: PredicateTemplateData, _2?: string) { }

  private submitDialog() {
    if (this.formState.isInvalid) {
      return;
    }

    this.onSubmit({
      ...this.formState.value,
      parameters: this.formState.value.parameters.map(p => ({ ...p })),
    }, this.templateId);

    this.closeDialog();
  }

  private cancelDialog() {
    this.closeDialog();
  }

  private closeDialog() {
    this.dialogIsOpen = false;
  }

  render() {
    return (
      <Form formState={this.formState} onAction={a => this.formState = formReducer(this.formState, a)}>
        <div class={`modal ${this.dialogIsOpen ? `is-active` : ``}`}>
          <div class='modal-background' />
          <div class='modal-card'>
            <header class='modal-card-head'>
              <p class='modal-card-title'>
                {!this.templateId ? `Create new predicate template` : `Edit predicate template`}
              </p>
            </header>

            <section class='modal-card-body'>
              <PredicateTemplateForm formState={this.formState} onAction={a => this.formState = formReducer(this.formState, a)} />
            </section>

            <footer class='modal-card-foot justify-content flex-end'>
              <button
                class='button is-danger is-outlined'
                type='button'
                onClick={() => this.cancelDialog()}
              >
                Cancel
              </button>
              <button
                class='button is-success'
                onClick={() => this.submitDialog()}
                disabled={this.formState.isInvalid && this.formState.isSubmitted}
              >
                Save
              </button>
            </footer>
          </div>
        </div>
      </Form>
    );
  }
}
</script>

<style scoped lang="scss">
.button {
  transition-duration: 0ms;
}
</style>

// src/ui/app/configuration/predicate-templates-page/predicate-template-dialog/predicate-template-dialog.component.ts
import { ChangeDetectionStrategy, Component, Input, OnDestroy } from '@angular/core';
import { ActionsSubject } from '@ngrx/store';
import { Subscription } from 'rxjs';
import { delay, filter, map } from 'rxjs/operators';

import {
  CancelPredicateTemplateDialogAction,
  PredicateTemplateDialogClosedAction,
  PredicateTemplateDialogSubmitSuccessfulAction,
  SubmitPredicateTemplateDialogAction,
} from './predicate-template-dialog.actions';
import { PredicateTemplateDialogState } from './predicate-template-dialog.state';

@Component({
  selector: 'sim-predicate-template-dialog',
  templateUrl: './predicate-template-dialog.component.html',
  styleUrls: ['./predicate-template-dialog.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PredicateTemplateDialogComponent implements OnDestroy {
  @Input() state: PredicateTemplateDialogState;

  private subscriptions: Subscription[] = [];

  constructor(private actionsSubject: ActionsSubject) {
    // this signals the end of the fade out animation of the dialog which
    // allows the state to set the properties required to ensure all
    // animations play properly
    this.subscriptions.push(
      actionsSubject.pipe(
        filter(a => a.type === PredicateTemplateDialogSubmitSuccessfulAction.TYPE || a.type === CancelPredicateTemplateDialogAction.TYPE),
        map(() => new PredicateTemplateDialogClosedAction()),
        delay(200),
      ).subscribe(actionsSubject)
    );
  }

  cancelDialog() {
    this.actionsSubject.next(new CancelPredicateTemplateDialogAction());
  }

  submitDialog() {
    if (this.state.formState.isInvalid) {
      return;
    }

    this.actionsSubject.next(new SubmitPredicateTemplateDialogAction(this.state.formState.value, this.state.templateId));
  }

  ngOnDestroy() {
    this.subscriptions.forEach(s => s.unsubscribe());
  }
}

<form [ngrxFormState]="state.formState">
  <div class="modal"
       [class.is-active]="state.dialogIsOpen && !state.dialogIsClosing">
    <div class="modal-background"></div>
    <div class="modal-card">

      <header class="modal-card-head">
        <p class="modal-card-title"
           *ngIf="state.isNewItem">
          Create new predicate template
        </p>
        <p class="modal-card-title"
           *ngIf="!state.isNewItem">
          Edit predicate template
        </p>
      </header>

      <!--
        We remove the body from the DOM while the dialog is not open to
        prevent any animations from playing when the dialog is opened.
      -->
      <section class="modal-card-body"
               *ngIf="state.dialogIsOpen">
        <sim-predicate-template-form [formState]="state.formState"></sim-predicate-template-form>
      </section>

      <footer class="modal-card-foot justify-content flex-end">
        <button class="button is-danger is-outlined"
                type="button"
                (click)="cancelDialog()"
                [disabled]="state.isSaving">
          Cancel
        </button>
        <button class="button is-success"
                [class.is-loading]="state.isSaving"
                (click)="submitDialog()"
                [disabled]="state.formState.isInvalid && state.formState.isSubmitted">
          Save
        </button>
      </footer>
    </div>
  </div>
</form>
