// src/ui/app/configuration/predicate-templates-page/predicate-template-tile/predicate-template-tile.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { ActionsSubject } from '@ngrx/store';

import { OpenPredicateTemplateDialogAction } from '../predicate-template-dialog';
import { ParameterFormValue } from '../predicate-template-dialog/predicate-template-dialog.dto';
import { DeletePredicateTemplateAction } from './predicate-template-tile.actions';
import { PredicateTemplateTileState } from './predicate-template-tile.state';

@Component({
  selector: 'sim-predicate-template-tile',
  templateUrl: './predicate-template-tile.component.html',
  styleUrls: ['./predicate-template-tile.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PredicateTemplateTileComponent {
  @Input() state: PredicateTemplateTileState;

  constructor(private actionsSubject: ActionsSubject) { }

  delete() {
    this.actionsSubject.next(new DeletePredicateTemplateAction(this.state.templateId));
  }

  startEdit() {
    this.actionsSubject.next(
      new OpenPredicateTemplateDialogAction(
        {
          name: this.state.name,
          description: this.state.description,
          evalFunctionBody: this.state.evalFunctionBody,
          parameters: this.state.parameters.map<ParameterFormValue>(p => ({
            name: p.name,
            description: p.description,
            isRequired: p.isRequired,
            valueType: p.valueType as any,
            defaultValue: p.defaultValue as any,
          })),
        },
        this.state.templateId,
      )
    );
  }

  trackByIndex(idx: number) {
    return idx;
  }
}

<div class="box">
  <div class="level is-marginless is-mobile">
    <div class="level-left">
      <h2 class="name">
        {{ state.name }}
      </h2>
    </div>
    <div class="level-right">
      <div class="buttons is-marginless">
        <div>
          <button class="button is-danger"
                  type="button"
                  (click)="delete()">
            <span>Delete</span>
            <span class="icon is-small">
              <fa-icon icon="times"></fa-icon>
            </span>
          </button>
          <button class="button is-primary"
                  type="button"
                  (click)="startEdit()">
            <span>Edit</span>
            <span class="icon is-small">
              <fa-icon icon="edit"></fa-icon>
            </span>
          </button>
        </div>
      </div>
    </div>
  </div>

  <p class="description">
    {{ state.description }}
  </p>

  <label class="label">
    Function Body
  </label>
  <pre>{{ state.evalFunctionBody }}</pre>

  <div class="parameters">
    <div class="parameters-title">
      <label class="label">Parameters</label>
      <p *ngIf="state.parameters.length === 0">
        This predicate template does not have any parameters.
      </p>
    </div>

    <div class="box parameter"
         *ngFor="let parameter of state.parameters; let i = index; trackBy: trackByIndex">

      <h3 class="parameter-name">
        {{ parameter.name }}
      </h3>

      <p class="parameter-description">
        {{ parameter.description }}
      </p>

      <div class="columns">

        <div class="column is-narrow">
          <label class="label">Is Required?</label>
          <span>{{ parameter.isRequired ? 'Yes' : 'No' }}</span>
        </div>

        <div class="column is-narrow">
          <label class="label">Value Type</label>
          <span>{{ parameter.valueType }}</span>
        </div>

        <div class="column">
          <label class="label">Default Value</label>
          <span>{{ parameter.defaultValue }}</span>
        </div>

      </div>
    </div>
  </div>
</div>

// src/modules/predicate-template/predicate-template-tile.vue
<script lang="tsx">
import { Component, Prop } from 'vue-property-decorator';
import { Emit, TsxComponent } from '../../ui-infrastructure';
import predicateTemplates from './predicate-template.store';

export interface PredicateTemplateTileProps {
  templateId: string;
  onEdit: () => any;
  onDelete: () => any;
}

@Component({})
export default class PredicateTemplateTile extends TsxComponent<PredicateTemplateTileProps> implements PredicateTemplateTileProps {
  @Prop() templateId!: string;

  get template() {
    return predicateTemplates.state.templatesById[this.templateId];
  }

  @Emit()
  onEdit() { }

  @Emit()
  onDelete() { }

  render() {
    return (
      <div class='box root'>
        <div class='level is-marginless is-mobile'>
          <div class='level-left'>
            <h2 class='name'>
              {this.template.name}
            </h2>
          </div>
          <div class='level-right'>
            <div class='buttons is-marginless'>
              <div>
                <button
                  class='button is-danger'
                  type='button'
                  onClick={() => this.onDelete()}
                >
                  <span>Delete</span>
                  <span class='icon is-small'>
                    <fa-icon icon='times' />
                  </span>
                </button>
                <button
                  class='button is-primary'
                  type='button'
                  onClick={() => this.onEdit()}
                >
                  <span>Edit</span>
                  <span class='icon is-small'>
                    <fa-icon icon='edit' />
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>

        <p class='description'>
          {this.template.description}
        </p>

        <label class='label'>
          Function Body
        </label>
        <pre>{this.template.evalFunctionBody}</pre>

        <div class='parameters'>
          <div class='parameters-title'>
            <label class='label'>Parameters</label>
            {this.template.parameters.length === 0 &&
              <p>
                This predicate template does not have any parameters.
              </p>
            }
          </div>

          {
            this.template.parameters.map(parameter =>
              <div key={parameter.name} class='box parameter'>

                <h3 class='parameter-name'>
                  {parameter.name}
                </h3>

                <p class='parameter-description'>
                  {parameter.description}
                </p>

                <div class='columns'>

                  <div class='column is-narrow'>
                    <label class='label'>Is Required?</label>
                    <span>{parameter.isRequired ? 'Yes' : 'No'}</span>
                  </div>

                  <div class='column is-narrow'>
                    <label class='label'>Value Type</label>
                    <span>{parameter.valueType}</span>
                  </div>

                  <div class='column'>
                    <label class='label'>Default Value</label>
                    <span>{parameter.defaultValue}</span>
                  </div>

                </div>
              </div>
            )
          }
        </div>
      </div>
    );
  }
}
</script>

<style scoped lang="scss">
@import 'variables';
@import '~bulma/sass/utilities/mixins';

.root {
  height: 100%;
}

@include from($desktop) {
  .buttons {
    opacity: 0;
    transition: opacity ease 200ms;
  }

  .root:hover .buttons {
    opacity: 1;
  }
}

.name {
  font-size: 120%;
  font-weight: bold;
}

.description {
  margin-bottom: 1rem;
}

.parameters {
  padding-top: 1rem;
}

.parameters-title {
  margin-bottom: 0.5rem;
}

.parameter.box {
  border: 1px solid $background;
}

.parameter {
  padding-top: 0.75rem;
  padding-bottom: 0.75rem;
}

.parameter-name {
  font-weight: bold;
  margin-bottom: 0.5rem;
}

.parameter-description {
  margin-bottom: 0.5rem;
}
</style>
