// src/ui-infrastructure/navbar.vue
<script lang="tsx">
import { Component, Vue } from 'vue-property-decorator';

@Component({})
export default class Navbar extends Vue {
  menuIsOpen = false;

  toggleMenu() {
    this.menuIsOpen = !this.menuIsOpen;
  }

  closeMenu() {
    this.menuIsOpen = false;
  }

  render() {
    return (
      <nav
        class='navbar is-fixed-top'
        role='navigation'
        aria-label='main navigation'
      >
        <div class='container is-fluid'>

          <div class='navbar-brand'>
            <a
              role='button'
              class={`navbar-burger has-text-white${this.menuIsOpen ? ` is-active` : ``}`}
              onClick={() => this.toggleMenu()}
            >
              <span />
              <span />
              <span />
            </a>
          </div>

          <div class={`navbar-menu${this.menuIsOpen ? ` is-active` : ``}`}>
            <div class='navbar-start'>

              <router-link
                to='predicate-tree'
                class='navbar-item has-text-white'
                onClick={() => this.closeMenu()}
              >
                Predicate Tree
              </router-link>

              <router-link
                to='predicate-templates'
                class='navbar-item has-text-white'
                onClick={() => this.closeMenu()}
              >
                Predicate Templates
              </router-link>

              <router-link
                to='response-generator-templates'
                class='navbar-item has-text-white'
                onClick={() => this.closeMenu()}
              >
                Response Generator Templates
              </router-link>

            </div>

          </div>
        </div>
      </nav>
    );
  }
}
</script>

<style scoped lang='scss'>
</style>

// src/ui/app/infrastructure/navbar/navbar.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { ActionsSubject } from '@ngrx/store';

import { CloseMenuAction, ToggleMenuAction } from './navbar.actions';
import { NavbarState } from './navbar.state';

@Component({
  selector: 'sim-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavbarComponent {
  @Input() state: NavbarState;

  constructor(private actionsSubject: ActionsSubject) {}

  toggleMenu() {
    this.actionsSubject.next(new ToggleMenuAction());
  }

  closeMenu() {
    this.actionsSubject.next(new CloseMenuAction());
  }
}

<nav class="navbar is-fixed-top"
     role="navigation"
     aria-label="main navigation">
  <div class="container is-fluid">
    <div class="navbar-brand">
      <a role="button"
         class="navbar-burger has-text-white"
         [class.is-active]="state.menuIsOpen"
         (click)="toggleMenu()">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
    <div class="navbar-menu"
         [class.is-active]="state.menuIsOpen">
      <div class="navbar-start">
        <a class="navbar-item has-text-white"
           (click)="closeMenu()"
           predicateTreeLink>
          Predicate Tree
        </a>
        <a class="navbar-item has-text-white"
           (click)="closeMenu()"
           predicateKindsLink>
          Predicate Kinds
        </a>
        <a class="navbar-item has-text-white"
           (click)="closeMenu()"
           responseGeneratorKindsLink>
          Response Generator Kinds
        </a>
      </div>
    </div>
  </div>
</nav>
