// src/ui-infrastructure/form-components/form.tsx
import { Action, FormGroupState, MarkAsSubmittedAction } from 'pure-forms';
import { pure, PureComponentContext } from '../tsx';

export interface FormProps {
  formState: FormGroupState<any>;
  onAction: (action: Action) => any;
}

const FormDef = ({ formState, onAction }: FormProps, { slots }: PureComponentContext) => {
  return (
    <form novalidate='novalidate' onSubmit={onSubmit}>
      {slots.default}
    </form>
  );

  function onSubmit(e: Event) {
    e.preventDefault();
    onAction(new MarkAsSubmittedAction(formState.id));
  }
};

export const Form = pure(FormDef);

// src/ui-infrastructure/form-components/form.vue
<script lang="tsx">
import { Action, FormGroupState, MarkAsSubmittedAction } from 'pure-forms';
import { Component, Prop } from 'vue-property-decorator';
import { Emit } from '../decorators';
import { TsxComponent } from '../tsx-component';

export interface FormProps {
  formState: FormGroupState<any>;
  onAction: (action: Action) => any;
}

@Component({})
export class Form extends TsxComponent<FormProps> implements FormProps {
  @Prop() formState: FormGroupState<any>;

  @Emit()
  onAction(_: Action) { }

  private onSubmit(e: Event) {
    e.preventDefault();
    this.onAction(new MarkAsSubmittedAction(this.formState.id));
  }

  render() {
    return (
      <form novalidate='novalidate' onSubmit={(e: Event) => this.onSubmit(e)}>
        {this.$slots.default}
      </form>
    );
  }
}

export default Form;
</script>

<style scoped lang="scss">
</style>
